
#ifndef _C2_eq53_
#define _C2_eq53_

#ifdef __cplusplus
extern "C" {
#endif

extern void F68_948(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_949(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_950(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_951(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_952(EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER_32, EIF_INTEGER_32);
extern void F68_953(EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER_32, EIF_INTEGER_32);
extern void F68_954(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_955(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_956(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_957(EIF_REFERENCE, EIF_REFERENCE, EIF_CHARACTER_8, EIF_CHARACTER_8);
extern void F68_958(EIF_REFERENCE, EIF_REFERENCE, EIF_CHARACTER_8, EIF_CHARACTER_8);
extern void F68_959(EIF_REFERENCE, EIF_REFERENCE, EIF_BOOLEAN, EIF_BOOLEAN);
extern void F68_960(EIF_REFERENCE, EIF_REFERENCE, EIF_BOOLEAN, EIF_BOOLEAN);
extern void F68_961(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_962(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_963(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_964(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void F68_965(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F68_966(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F68_967(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F68_968(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F68_969(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F68_970(EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE);
extern void EIF_Minit53(void);
extern void F973_6344(EIF_REFERENCE, EIF_INTEGER_32);
extern EIF_BOOLEAN F965_5972(EIF_REFERENCE, EIF_REFERENCE);
extern void F67_944(EIF_REFERENCE, EIF_REFERENCE, EIF_BOOLEAN);
extern EIF_BOOLEAN F965_5975(EIF_REFERENCE, EIF_REFERENCE);
extern void F973_6302(EIF_REFERENCE, EIF_REFERENCE);
extern void F67_943(EIF_REFERENCE, EIF_REFERENCE, EIF_BOOLEAN);
extern void F971_6226(EIF_REFERENCE, EIF_INTEGER_32);
extern void F973_6340(EIF_REFERENCE, EIF_REFERENCE);
extern char *(*R2989[])();
extern char *(*R28[])();
extern char *(*R2962[])();

#ifdef __cplusplus
}
#endif

#endif
