
#ifndef _C1_on23_
#define _C1_on23_

#ifdef __cplusplus
extern "C" {
#endif

extern void F8_385(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F8_386(EIF_REFERENCE);
extern EIF_BOOLEAN F8_387(EIF_REFERENCE);
extern EIF_BOOLEAN F8_388(EIF_REFERENCE);
extern EIF_REFERENCE F8_389(EIF_REFERENCE);
extern EIF_REFERENCE F8_390(EIF_REFERENCE);
extern EIF_REFERENCE F8_391(EIF_REFERENCE);
extern EIF_REFERENCE F8_392(EIF_REFERENCE);
extern EIF_REFERENCE F8_393(EIF_REFERENCE);
extern EIF_REFERENCE F8_394(EIF_REFERENCE);
extern EIF_REFERENCE F8_395(EIF_REFERENCE);
extern EIF_BOOLEAN F8_396(EIF_REFERENCE, EIF_REFERENCE);
extern void F8_1(EIF_REFERENCE, int);
extern void EIF_Minit23(void);
extern EIF_BOOLEAN F968_6096(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F968_6088(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F567_3452(EIF_REFERENCE);
extern EIF_REFERENCE F1_14(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
