
#ifndef _C1_si22_
#define _C1_si22_

#ifdef __cplusplus
extern "C" {
#endif

extern void F7_374(EIF_REFERENCE);
extern EIF_REFERENCE F7_375(EIF_REFERENCE);
extern EIF_REFERENCE F7_376(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_377(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_378(EIF_REFERENCE);
extern EIF_BOOLEAN F7_379(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_380(EIF_REFERENCE);
extern EIF_REFERENCE F7_381(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_382(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_383(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F7_384(EIF_REFERENCE, EIF_REFERENCE);
extern void F7_1(EIF_REFERENCE, int);
extern void EIF_Minit22(void);
extern void F10_413(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F328_3289(EIF_REFERENCE);
extern void F4_344(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F4_346(EIF_REFERENCE);
extern void F3_338(EIF_REFERENCE);
extern void F10_411(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F328_3280(EIF_REFERENCE);
extern void F328_3295(EIF_REFERENCE);
extern EIF_BOOLEAN F825_4356(EIF_REFERENCE, EIF_REFERENCE);
extern void F3_330(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_INTEGER_32 F680_3918(EIF_REFERENCE);
extern EIF_REFERENCE F680_3915(EIF_REFERENCE);
extern void F6_360(EIF_REFERENCE, EIF_REFERENCE);
extern void F10_412(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_BOOLEAN F567_3452(EIF_REFERENCE);
extern EIF_BOOLEAN F2_119(EIF_REFERENCE, EIF_REFERENCE);
extern void F2_117(EIF_REFERENCE);
extern EIF_REFERENCE F2_120(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
