
#ifndef _C1_sy11_
#define _C1_sy11_

#ifdef __cplusplus
extern "C" {
#endif

static EIF_REFERENCE F19_262_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_262(EIF_REFERENCE);
static EIF_REFERENCE F19_263_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_263(EIF_REFERENCE);
static EIF_REFERENCE F19_264_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_264(EIF_REFERENCE);
static EIF_REFERENCE F19_265_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_265(EIF_REFERENCE);
static EIF_REFERENCE F19_266_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_266(EIF_REFERENCE);
static EIF_REFERENCE F19_267_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_267(EIF_REFERENCE);
static EIF_REFERENCE F19_268_body(EIF_REFERENCE);
extern EIF_REFERENCE F19_268(EIF_REFERENCE);
extern void EIF_Minit11(void);
extern void F21_277(EIF_REFERENCE, EIF_REFERENCE);
extern EIF_REFERENCE F20_272(EIF_REFERENCE);
extern EIF_REFERENCE F20_271(EIF_REFERENCE);
extern EIF_REFERENCE F20_270(EIF_REFERENCE);
extern EIF_REFERENCE F60_809(EIF_REFERENCE);
extern EIF_REFERENCE F60_808(EIF_REFERENCE);
extern EIF_REFERENCE F60_807(EIF_REFERENCE);

#ifdef __cplusplus
}
#endif

#endif
