/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"
#include "eoffsets.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F968_6060();
extern void F968_6064();
extern void F971_6226();
extern void F971_6231();
extern void F679_3907();
extern void F960_5907();
extern void F157_1611();
extern EIF_REFERENCE F157_1598();
extern EIF_BOOLEAN F157_1610();
extern EIF_BOOLEAN F157_1618();
extern void F157_1620();
extern void F157_1621();
extern void F157_1622();
extern void egc_routine_tables_init (void);

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;
extern char *(*R2[])();
extern char *(*R6[])();
extern char *(*R3[])();

extern char *(*R4[])();

extern char *(*R5[])();



extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_REFERENCE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F968_6060;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER)) F968_6064;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_INTEGER)) F971_6226;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_INTEGER)) F971_6231;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_INTEGER)) F679_3907;
	egc_str_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_str32_count_offset = + _LNGOFF_1_1_0_2_;
	egc_str32_hash_offset = + _LNGOFF_1_1_0_0_;
	egc_routdisp_fl = (void (*)(EIF_REFERENCE, EIF_POINTER, EIF_POINTER, EIF_POINTER, EIF_REFERENCE, EIF_BOOLEAN, EIF_INTEGER)) F960_5907;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN, EIF_INTEGER, EIF_INTEGER, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_REFERENCE, EIF_INTEGER, EIF_BOOLEAN)) F157_1611;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F157_1610;
	egc_last_exception = (EIF_REFERENCE (*)(EIF_REFERENCE)) F157_1598;
	egc_is_code_ignored = (EIF_BOOLEAN (*)(EIF_REFERENCE, EIF_INTEGER)) F157_1618;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_REFERENCE)) F157_1620;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F157_1621;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F157_1622;

	egc_str_dtype = 969;

	egc_immstr8_dtype = 968;

	egc_str32_dtype = 972;

	egc_immstr32_dtype = 971;
	egc_arr_dtype = 678;
	egc_tup_dtype = 886;
	egc_disp_rout_id = 2235;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x02FB;
	egc_sp_wchar = 0x02FA;
	egc_sp_bool = 0x0305;
	egc_sp_uint8 = 0x02FE;
	egc_sp_uint16 = 0x0304;
	egc_sp_uint32 = 0x02FD;
	egc_sp_uint64 = 0x02F9;
	egc_sp_int8 = 0x0302;
	egc_sp_int16 = 0x0301;
	egc_sp_int32 = 0x02F8;
	egc_sp_int64 = 0x0303;
	egc_sp_real32 = 0x02FF;
	egc_sp_real64 = 0x0300;
	egc_sp_pointer = 0x02FC;
	egc_sp_ref = 0x02F7;

	egc_uint8_dtype = 907;
	egc_uint16_dtype = 925;
	egc_uint32_dtype = 904;
	egc_uint64_dtype = 901;
	egc_int8_dtype = 898;
	egc_int16_dtype = 895;
	egc_int32_dtype = 892;
	egc_int64_dtype = 889;
	egc_bool_dtype = 922;
	egc_real32_dtype = 910;
	egc_char_dtype = 919;
	egc_wchar_dtype = 916;
	egc_real64_dtype = 913;
	egc_point_dtype = 958;

	egc_exception_dtype = 116;
	egc_except_emnger_dtype = 156;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	exception_stack_managed = (EIF_BOOLEAN) 1;
	egc_ecreate = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R2;
	egc_exp_create = (void (**)(EIF_REFERENCE)) R6;
	egc_edispose = (void (**)(void)) R3;
	egc_copy = (void (**)(EIF_REFERENCE, EIF_REFERENCE)) R4;
	egc_is_equal = (EIF_BOOLEAN (**)(EIF_REFERENCE, EIF_REFERENCE)) R5;
	egc_ce_rname = egc_ce_rname_init;
	egc_fnbref = egc_fnbref_init;
	egc_fsize = egc_fsize_init;

	egc_system_name = "simple_onnx";
	egc_system_location = "D:\\prod\\simple_onnx\\EIFGENs\\simple_onnx_tests\\F_code";
	egc_compiler_tag = 39;
	egc_project_version = 1769946548;
	egc_has_old_special_semantic = 0;
	scount = 991;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "TEST_APP.make";
	egc_rcdt[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_routine_tables_init();
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 48; /* TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 229; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 990; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
